language: ruby
rvm:
  - 2.2.2

addons:
  postgresql: "9.3"

script:
  - RAILS_ENV=test bundle exec rake db:schema:load --trace
  - bundle exec rspec

before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database g5_phone_number_service_test;' -U postgres
